[tool.poetry]
name = "scope_foundry_test"
version = "0.1.0"
description = ""
authors = ["amcar-dtu <amcar@dtu.dk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scopefoundry = "^2.0.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
