from qtpy import QtWidgets
import pyqtgraph as pg

from ScopeFoundry.data_browser import DataBrowserView

from .random_number_gen_h5_data_loaders import load_number_gen_readout_simple


# viewers/random_number_gen.py
from qtpy import QtWidgets
import pyqtgraph as pg

from ScopeFoundry.data_browser import DataBrowserView

# Import the load function from the h5_data_loader.py file generated by Analyze with ipynb.
from .random_number_gen_h5_data_loaders import load_number_gen_readout_simple


class RandomNumberGenView(DataBrowserView):

    # This name is used in the GUI for the DataBrowser
    name = "number_gen_readout_simple"

    def setup(self):
        self.setup_figure()

    def on_change_data_filename(self, fname):
        self.data = load_number_gen_readout_simple(fname)
        self.update_display()

    def setup_figure(self):
        """
        Runs once during app initialization and is responsible
        for creating the widget `self.ui`.
        """
        self.ui = QtWidgets.QWidget()
        layout = QtWidgets.QVBoxLayout()
        self.ui.setLayout(layout)

        # Create a plot widget
        self.graphics_widget = pg.GraphicsLayoutWidget(border=(100, 100, 100))
        self.plot = self.graphics_widget.addPlot(title=self.name)
        self.plot_lines = {"y": self.plot.plot(pen="g")}
        layout.addWidget(self.graphics_widget)

    def update_display(self):
        self.plot_lines["y"].setData(self.data.y)  # NEEDED MODIFICATION HERE
